### ISSUE TITLE
Styling / a11y: Links are not noticable

### ISSUE THREAD

**Issue by bodograumann** [tailwindlabs/tailwindcss.com#1122]
It is impossible to detect inline links. The only difference is, that the mouse pointer changes on hover.
E.g. “content configuration” in the following is a link:
![Screenshot_20220110-131348](https://user-images.githubusercontent.com/1223583/148764511-bcceb6dc-48e7-44ba-ab49-b40f6eb6d783.png)

Cf. https://tailwindcss.com/docs/upgrade-guide

While I am at it, headers are also weirdly unstyled:
![Screenshot_20220110-132249](https://user-images.githubusercontent.com/1223583/148765395-c59adad7-a077-47d8-af6b-bccc00703f04.png)
Cf. https://tailwindcss.com/docs/content-configuration#using-regular-expressions

And when linking to a section, the page header overlaps the top of the targeted section.

This seems to be related to the qutebrowser :thinking:

**Comment by bodograumann** [comment]
Relevant style block that works in latest firefox / chromium:
```css
.prose :where(h3):not(:where([class~="not-prose"] *)) {
    color: #0f172a;
    font-weight: 600;
    font-size: 1.25em;
    margin-top: 2.4em;
    margin-bottom: .6em;
    line-height: 1.4;
}
```

`:where` is [not supported](https://caniuse.com/?search=%3Awhere) in chromium-87, on which the latest qt5-webengine version 5.15.8 is based.
It should degrade more gracefully imho.
