### ISSUE TITLE
Preflight img/video missing documentation

### ISSUE THREAD

**Issue by nous-** [tailwindlabs/tailwindcss.com#1374]
Version: 3.1.5.  Please update the [documentation](https://tailwindcss.com/docs/preflight#images-are-block-level) around img/video for this provision found in preflight.css:

```css
/*
Constrain images and videos to the parent width and preserve their intrinsic aspect ratio. (https://github.com/mozdevs/cssremedy/issues/14)
*/

img,
video {
  max-width: 100%;
  height: auto;
}
```
