### ISSUE TITLE
Responsive Container

### ISSUE THREAD

**Issue by rakesh02123** [tailwindlabs/tailwindcss.com#1845]
![tailwindcss-issue](https://github.com/user-attachments/assets/41583be6-2c94-4241-b3ba-76371a85973f)
In Responsive Container page, the break point is written max-width. It will not be max-width, it will be min-width.

**Comment by adamwathan** [comment]
Hey! The docs for this are correct, you can see in the generated CSS that the `container` class sets the `max-width` CSS property:

```css
.container {
  width: 100%;
}
@media (min-width: 640px) {
  .container {
    max-width: 640px;
  }
}
@media (min-width: 768px) {
  .container {
    max-width: 768px;
  }
}
@media (min-width: 1024px) {
  .container {
    max-width: 1024px;
  }
}
@media (min-width: 1280px) {
  .container {
    max-width: 1280px;
  }
}
@media (min-width: 1536px) {
  .container {
    max-width: 1536px;
  }
}
```

You're right that the breakpoints are min-width breakpoints but that's not what this table is showing.
