### ISSUE TITLE
Default theme variables without variants

### ISSUE THREAD

**Issue by MickL** [tailwindlabs/tailwindcss.com#2117]
Hello,

[Here](https://tailwindcss.com/docs/theme#default-theme-variable-reference) the docs say:

>For reference, here's a complete list of the theme variables included by default when you import Tailwind CSS into your project

But this doesnt seem entirely true because when [disabling the default theme](https://tailwindcss.com/docs/theme#using-a-custom-theme):

```css
@import "tailwindcss";

@theme {
  --*: initial;

  --radius-xs: 0.125rem;
  --radius-sm: 0.25rem;
  --radius-md: 0.375rem;
  --radius-lg: 0.5rem;
  --radius-xl: 0.75rem;
  --radius-2xl: 1rem;
  --radius-3xl: 1.5rem;
  --radius-4xl: 2rem;
}
```

Default variants like `shadow` or `rounded` dont work anymore, instead only with specific variants e.g.`shadow-md` and  `rounded-md`.

Therefor I guess there must be variables, currently not shown in the docs, that set:

```css
--radius: var(--radius-md)
```

or:

```css
--radius-base: var(--radius-md)
```

Or how can the default variants be defined? This info is missing from the docs.
