### ISSUE TITLE
--transition-duration-* supported but not documented

### ISSUE THREAD

**Issue by aparajita** [tailwindlabs/tailwindcss.com#2225]
I added this to my `@theme` section:

```css
--transition-duration-std: var(--p-transition-duration);
```

The corresponding `duration-std` class was correctly created by Tailwind:

```css
.duration-std {
    --tw-duration: var(--transition-duration-std) /* var(--p-transition-duration) */;
    transition-duration: var(--transition-duration-std) /* var(--p-transition-duration) */;
}
@property --tw-duration {
    syntax: "*";
    inherits: false;
}
```

This leads me to believe that `--transition-duration-*` IS a supported theme variable namespace, but it is not listed in the [relevant docs](https://tailwindcss.com/docs/theme#theme-variable-namespaces).
