### ISSUE TITLE
first-child variant plugin example doesn't quite work

### ISSUE THREAD

**Issue by aparajita** [tailwindlabs/tailwindcss.com#61]
Hmm... maybe I'm missing something, but this example doesn't really work:

```js
addVariant('first-child', ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.first-child${separator}${className}:first-child`
    })
  })
```

Here's what it generates if I add the 'first-child' variant to the borderWidth module:

```css
.first-child\:border-0:first-child {
  border-width: 0;
}

.first-child\:border-1:first-child {
  border-width: 1px;
}

/* and so on */
```

The only way this works is if the markup looks like this, because `:first-child` applies the first sibling that has the selector preceding it:

```html
<div>
  <div class="border-1 first-child:border-0">
  <div class="border-1 first-child:border-0">
  <div class="border-1 first-child:border-0">
</div>
```

Is that really the intended usage of the example? Maybe you meant something like this, which seems more natural:

```html
<div class="first-child:border-0">
  <div class="border-1">
  <div class="border-1">
  <div class="border-1">
</div>
```

For that usage to work, the code has to be:

```js
  addVariant('first-child', ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.first-child${separator}${className} > *:first-child`
    })
  })
```

which generates:

```css
.first-child\:border-0 > *.first-child {
  border-width: 0;
}
```

which I believe is the intended result.
