### ISSUE TITLE
misleading animation css docs on keyframes

### ISSUE THREAD

**Issue by ironmanvim** [tailwindlabs/tailwindcss.com#692]
I have been working with animation in our project.
I used the ping animation for ping effect.
I have used opacity-0 with delayed animation.
but as of docs it should work. 
'but why the hell the animation is not working'.
tinkering about that. checked the default config.

The default keyframe of ping in defaultConfig is
```js
ping: {
        '75%, 100%': {
          transform: 'scale(2)',
          opacity: '0',
        },
      },
```
But the docs says
```css
keyframes ping {
  0% {
    transform: scale(1);
    opacity: 1;
  }
  75%, 100% {
    transform: scale(2);
    opacity: 0;
  }
}
```
This is a misleading info.
`ping`, `spin`, `pulse` are just like that.
