### ISSUE TITLE
Manual dark mode and text opacity (and others) don't get inherited

### ISSUE THREAD

**Issue by royvanv** [tailwindlabs/tailwindcss.com#768]
If [dark mode is set manual](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) (class based) The following example code will not apply the text opacity in dark mode. I think this should be noted in the docs. 

```html
<div class="text-black dark:text-white text-opacity-25">Barely visible text</div>
```

The cause of this behaviour is not a bug in Tailwind, but an effect of the specificity in CSS. `.dark .dark\:text-white` simply resets the `--tw-text-opacity` variable to `1`.

This behaviour will affect other utilities as well, such as transitions.

**Comment by royvanv** [comment]
The code would work if the text color plugin would be using the 2 parameter of the `val` method in CSS.

```css
// Current - does not work with dark mode
.text-black {
   --tw-text-opacity: 1;
    color: rgba(0, 0, 0, var(--tw-text-opacity));
}

// Fix - works well with dark mode
.text-black {
    color: rgba(0, 0, 0, var(--tw-text-opacity, 1));
}
```
