### ISSUE TITLE
@tailwind and @layer works well in one file but how to split them into several files?

### ISSUE THREAD

**Issue by existe-deja** [tailwindlabs/tailwindcss.com#991]
I have a main repository and a home made ui library repository. I want my UI library to take care of default across several projects.
I use jit mode for every projects.

What I did is I inject the `tailwind.config.js` file from my lib as a preset of projects who wants to use it.
Problem is at some point, in the UI library I required to define some global css like basic style for inputs. To do so I added @layer directives in the ui library but it required to import @tailwind directives first.
In the main project I imported the global css of my UI lib but now I have imported @tailwind twice and I experience some weird overrides.

I found the doc on how things are imported a bit succinct specially if you want to split a big file into several pieces (base.css, components.css, utilities.css, ...) and even if I want to split a layer into multiple files like btn.css, link.css, ...

More info is welcomed!

Thanks :pray:

**Comment by adamwathan** [comment]
Hey! You should use `postcss-import` to do this to make sure that all of your files are combined into one before being passed to Tailwind:

https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports

Hope that helps.

**Comment by existe-deja** [comment]
Thanks for answering me.
I'm not sure to fully understand. By using postcss-import + @import directive if I have the right order in my main style file I can get rid off `@layer`?

Because I can't use `@layer` in a splitted file as I got the error `@layer components is used but no matching @tailwind components directive is present.`

**Comment by adamwathan** [comment]
Can you create a "help" discussion here and include an example project of how you have things currently set up?

https://github.com/tailwindlabs/tailwindcss/discussions

That will be the easiest way to show you what you need to change.

Generally you just need to add `postcss-import` to the beginning of your plugin list as documented in that page I sent you, then `@layer` will work in all of your files as long as they are being imported.

```css
/* main.css */
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@import './file-1.css';
@import './file-2.css';

/* file-1.css */
@layer utilities {
  .custom-utility {
    banana: sandwich;
  }
}

/* file-2.css */
@layer components {
  .custom-component {
    chocolate: muffin;
  }
}
```

```js
// postcss.config.js
module.exports = {
  plugins: {
    'postcss-import': {},
    'tailwindcss': {},
    'autoprefixer': {},
  }
}
```
